# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  ADMIN_EMAIL_VAR: wuhanstudio@qq.com
  ACME_PATH_VAR:   /data/acme

env:
  ADMIN_EMAIL: '{{.ADMIN_EMAIL_VAR}}'
  ACME_PATH:   '{{.ACME_PATH_VAR}}'

tasks:
  traefik:
    desc: Install traefik with TLS support
    cmds:
      - envsubst < traefik-config.yml | kubectl apply -f -

  status:
    desc: Check installation status
    cmds:
      - kubectl get all
      - kubectl get all -n kube-system
